/************************************* 개별 프로덕트 카드 *************************************/


$(document).ready(function () {

    var product_01 = "";
    product_01 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_01 +=     '<div class="item_head">'; 
    product_01 +=        '<div class="box_line_gray newly_added">'; 
    product_01 +=           '<div class="wrap_img">'; 
    product_01 +=              '<img src="../img/saas_img/4_privateSaaS/logo_01.png" alt="센스메일 클라우드 로고 이미지" class="viewer"/>'; 
    product_01 +=            '</div>'; 
    product_01 +=            '<span class="newly_added_tag">NEW</span>'; 
    product_01 +=        '</div>'; 
    product_01 +=        '<div class="box_filled">'; 
    product_01 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_01 +=        '</div>'; 
    product_01 +=     '</div>';  
    product_01 +=     '<div class="item_middle">'; 
    product_01 +=        '<div class="wrap_name">'; 
    product_01 +=           '<span class="service_category">메일</span>'; 
    product_01 +=           '<span class="product_name">센스메일 클라우드 (SensMail Cloud)</span>'; 
    product_01 +=           '<span class="company_name">아이모션</span>'; 
    product_01 +=           '<div class="wrap_serviceTag">'; 
    product_01 +=              '<span class="search_tag">메일</span>'; 
    product_01 +=              '<span class="search_tag">그룹웨어</span>'; 
    product_01 +=           '</div>'; 
    product_01 +=           '<div class="wrap_govSaas">'; 
    product_01 +=              '<p>정부 공통시스템 연계</p>'; 
    product_01 +=              '<div class="govSaas_tag">'; 
    product_01 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_01 +=                 '<span class="tag">행정표준코드</span>'; 
    product_01 +=                 '<span class="tag">LDAP</span>'; 
    product_01 +=                 '<span class="tag">GPKI</span>'; 
    product_01 +=              '</div>'; 
    product_01 +=           '</div>'; 
    product_01 +=         '</div>'; 
    product_01 +=         '<div class="wrap_detail_info">'; 
    product_01 +=             '<ul>'; 
    product_01 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">표준</span></li>'; 
    product_01 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_01 +=                '<li><span class="label">이용 인프라</span><span class="info_value">네이버 클라우드(공공)</span></li>'; 
    product_01 +=             '</ul>'; 
    product_01 +=          '</div>'; 
    product_01 +=      '</div>';   
    product_01 +=      '<div class="item_buttons">';  
    product_01 +=         '<div class="btn_top">'; 
    product_01 +=            '<div class="wrap_btn">';
    product_01 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_01 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_01 +=               '</div>'; 
    product_01 +=            '</div>'; 
    product_01 +=         '</div>'; 
    product_01 +=         '<div class="btn_bottom">'; 
    product_01 +=            '<div class="wrap_btn">';
    product_01 +=              '<p>기관직접계약</p>'; 
    product_01 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_01 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_01 +=               '</div>'; 
    product_01 +=            '</div>'; 
    product_01 +=            '<div class="wrap_btn">';
    product_01 +=              '<p>중앙조달계약</p>'; 
    product_01 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_01 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_01 +=               '</div>'; 
    product_01 +=            '</div>'; 
    product_01 +=         '</div>'; 
    product_01 +=       '</div>'; 
    product_01 +=    '</div>'; 

    $(".product_card.product_01").html(product_01);

    var product_02 = "";
    product_02 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_02 +=     '<div class="item_head">'; 
    product_02 +=        '<div class="box_line_gray newly_added">'; 
    product_02 +=           '<div class="wrap_img">'; 
    product_02 +=              '<img src="../img/saas_img/4_privateSaaS/logo_02.png" alt="StrategyGATE 로고 이미지" class="viewer"/>'; 
    product_02 +=            '</div>'; 
    product_02 +=            '<span class="newly_added_tag">NEW</span>'; 
    product_02 +=        '</div>'; 
    product_02 +=        '<div class="box_filled">'; 
    product_02 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_02 +=        '</div>'; 
    product_02 +=     '</div>';  
    product_02 +=     '<div class="item_middle">'; 
    product_02 +=        '<div class="wrap_name">'; 
    product_02 +=           '<span class="service_category">성과 관리</span>'; 
    product_02 +=           '<span class="product_name">StrategyGATE (전략성과관리솔루션)</span>'; 
    product_02 +=           '<span class="company_name">이즈파크</span>'; 
    product_02 +=           '<div class="wrap_serviceTag">'; 
    product_02 +=              '<span class="search_tag">경영성과 관리</span>'; 
    product_02 +=              '<span class="search_tag">성과관리</span>'; 
    product_02 +=              '<span class="search_tag">전략</span>'; 
    product_02 +=              '<span class="search_tag">개인성과평가</span>'; 
    product_02 +=              '<span class="search_tag">성과모니터링</span>'; 
    product_02 +=              '<span class="search_tag">성과평가</span>'; 
    product_02 +=              '<span class="search_tag">정부경영평가</span>'; 
    product_02 +=           '</div>'; 
    product_02 +=           '<div class="wrap_govSaas">'; 
    product_02 +=              '<p>정부 공통시스템 연계</p>'; 
    product_02 +=              '<div class="govSaas_tag">'; 
    product_02 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_02 +=                 '<span class="tag">행정표준코드</span>'; 
    product_02 +=                 '<span class="tag">LDAP</span>'; 
    product_02 +=              '</div>'; 
    product_02 +=           '</div>'; 
    product_02 +=         '</div>'; 
    product_02 +=         '<div class="wrap_detail_info">'; 
    product_02 +=             '<ul>'; 
    product_02 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_02 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_02 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_02 +=             '</ul>'; 
    product_02 +=          '</div>'; 
    product_02 +=      '</div>';   
    product_02 +=      '<div class="item_buttons">';  
    product_02 +=         '<div class="btn_top">'; 
    product_02 +=            '<div class="wrap_btn">';
    product_02 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_02 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_02 +=               '</div>'; 
    product_02 +=            '</div>'; 
    product_02 +=         '</div>'; 
    product_02 +=         '<div class="btn_bottom">'; 
    product_02 +=            '<div class="wrap_btn">';
    product_02 +=              '<p>기관직접계약</p>'; 
    product_02 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_02 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_02 +=               '</div>'; 
    product_02 +=            '</div>'; 
    product_02 +=            '<div class="wrap_btn">';
    product_02 +=              '<p>중앙조달계약</p>'; 
    product_02 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_02 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_02 +=               '</div>'; 
    product_02 +=            '</div>'; 
    product_02 +=         '</div>'; 
    product_02 +=       '</div>'; 
    product_02 +=    '</div>'; 

    $(".product_card.product_02").html(product_02);

    var product_03 = "";
    product_03 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_03 +=     '<div class="item_head">'; 
    product_03 +=        '<div class="box_line_gray newly_added">'; 
    product_03 +=           '<div class="wrap_img">'; 
    product_03 +=              '<img src="../img/saas_img/4_privateSaaS/logo_03.png" alt="페어리 로고 이미지" class="viewer"/>'; 
    product_03 +=            '</div>'; 
    product_03 +=            '<span class="newly_added_tag">NEW</span>'; 
    product_03 +=        '</div>'; 
    product_03 +=        '<div class="box_filled">'; 
    product_03 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_03 +=        '</div>'; 
    product_03 +=     '</div>';  
    product_03 +=     '<div class="item_middle">'; 
    product_03 +=        '<div class="wrap_name">'; 
    product_03 +=           '<span class="service_category">채용 · 인사 관리</span>'; 
    product_03 +=           '<span class="product_name">페어리</span>'; 
    product_03 +=           '<span class="company_name">주식회사 휴스테이션</span>'; 
    product_03 +=           '<div class="wrap_serviceTag">'; 
    product_03 +=              '<span class="search_tag">채용 관리</span>'; 
    product_03 +=              '<span class="search_tag">채용공고</span>'; 
    product_03 +=              '<span class="search_tag">합격자 발표</span>'; 
    product_03 +=           '</div>'; 
/*     product_03 +=           '<div class="wrap_govSaas">'; 
    product_03 +=              '<p>정부 공통시스템 연계</p>'; 
    product_03 +=              '<div class="govSaas_tag">'; 
    product_03 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_03 +=                 '<span class="tag">행정표준코드</span>'; 
    product_03 +=                 '<span class="tag">LDAP</span>'; 
    product_03 +=              '</div>'; 
    product_03 +=           '</div>';  */
    product_03 +=         '</div>'; 
    product_03 +=         '<div class="wrap_detail_info">'; 
    product_03 +=             '<ul>'; 
    product_03 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_03 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_03 +=                '<li><span class="label">이용 인프라</span><span class="info_value">카카오</span></li>'; 
    product_03 +=             '</ul>'; 
    product_03 +=          '</div>'; 
    product_03 +=      '</div>';   
    product_03 +=      '<div class="item_buttons">';  
    product_03 +=         '<div class="btn_top">'; 
    product_03 +=            '<div class="wrap_btn">';
    product_03 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_03 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_03 +=               '</div>'; 
    product_03 +=            '</div>'; 
    product_03 +=         '</div>'; 
    product_03 +=         '<div class="btn_bottom">'; 
    product_03 +=            '<div class="wrap_btn">';
    product_03 +=              '<p>기관직접계약</p>'; 
    product_03 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_03 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_03 +=               '</div>'; 
    product_03 +=            '</div>'; 
/*     product_03 +=            '<div class="wrap_btn">';
    product_03 +=              '<p>중앙조달계약</p>'; 
    product_03 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_03 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_03 +=               '</div>'; 
    product_03 +=            '</div>';  */
    product_03 +=         '</div>'; 
    product_03 +=       '</div>'; 
    product_03 +=    '</div>'; 

    $(".product_card.product_03").html(product_03);
    
    var product_04 = "";
    product_04 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_04 +=     '<div class="item_head">'; 
    product_04 +=        '<div class="box_line_gray" data-aos="fade" data-aos-delay="100">'; 
    product_04 +=           '<div class="wrap_img">'; 
    product_04 +=              '<img src="../img/saas_img/4_privateSaaS/logo_04.png" alt="ORG Insight 로고 이미지" class="viewer"/>'; 
    product_04 +=            '</div>'; 
    product_04 +=        '</div>'; 
    product_04 +=        '<div class="box_filled">'; 
    product_04 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_04 +=        '</div>'; 
    product_04 +=     '</div>';  
    product_04 +=     '<div class="item_middle">'; 
    product_04 +=        '<div class="wrap_name">'; 
    product_04 +=           '<span class="service_category">채용 · 인사 관리</span>'; 
    product_04 +=           '<span class="product_name">ORG Insight (CG)</span>'; 
    product_04 +=           '<span class="company_name">㈜소프트인</span>'; 
    product_04 +=           '<div class="wrap_serviceTag">'; 
    product_04 +=              '<span class="search_tag">인사 관리</span>'; 
    product_04 +=              '<span class="search_tag">조직 시각화</span>'; 
    product_04 +=              '<span class="search_tag">인사 정보 시각화</span>'; 
    product_04 +=           '</div>'; 
/*     product_04 +=           '<div class="wrap_govSaas">'; 
    product_04 +=              '<p>정부 공통시스템 연계</p>'; 
    product_04 +=              '<div class="govSaas_tag">'; 
    product_04 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_04 +=                 '<span class="tag">행정표준코드</span>'; 
    product_04 +=                 '<span class="tag">LDAP</span>'; 
    product_04 +=              '</div>'; 
    product_04 +=           '</div>';  */
    product_04 +=         '</div>'; 
    product_04 +=         '<div class="wrap_detail_info">'; 
    product_04 +=             '<ul>'; 
    product_04 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_04 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_04 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_04 +=             '</ul>'; 
    product_04 +=          '</div>'; 
    product_04 +=      '</div>';   
    product_04 +=      '<div class="item_buttons">';  
    product_04 +=         '<div class="btn_top">'; 
    product_04 +=            '<div class="wrap_btn">';
    product_04 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_04 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_04 +=               '</div>'; 
    product_04 +=            '</div>'; 
    product_04 +=         '</div>'; 
    product_04 +=         '<div class="btn_bottom">'; 
    product_04 +=            '<div class="wrap_btn">';
    product_04 +=              '<p>기관직접계약</p>'; 
    product_04 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_04 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_04 +=               '</div>'; 
    product_04 +=            '</div>'; 
    product_04 +=            '<div class="wrap_btn">';
    product_04 +=              '<p>중앙조달계약</p>'; 
    product_04 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_04 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_04 +=               '</div>'; 
    product_04 +=            '</div>'; 
    product_04 +=         '</div>'; 
    product_04 +=       '</div>'; 
    product_04 +=    '</div>'; 

    $(".product_card.product_04").html(product_04);

    var product_05 = "";
    product_05 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_05 +=     '<div class="item_head">'; 
    product_05 +=        '<div class="box_line_gray" data-aos="fade" data-aos-delay="100">'; 
    product_05 +=           '<div class="wrap_img">'; 
    product_05 +=              '<img src="../img/saas_img/4_privateSaaS/logo_05.png" alt="엔로비 로고 이미지" class="viewer"/>'; 
    product_05 +=            '</div>'; 
    product_05 +=        '</div>'; 
    product_05 +=        '<div class="box_filled">'; 
    product_05 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_05 +=        '</div>'; 
    product_05 +=     '</div>';  
    product_05 +=     '<div class="item_middle">'; 
    product_05 +=        '<div class="wrap_name">'; 
    product_05 +=           '<span class="service_category">출입 관리</span>'; 
    product_05 +=           '<span class="product_name">엔로비 (nlobby)</span>'; 
    product_05 +=           '<span class="company_name">엔로비</span>'; 
    product_05 +=           '<div class="wrap_serviceTag">'; 
    product_05 +=              '<span class="search_tag">출입관리</span>'; 
    product_05 +=              '<span class="search_tag">방문객</span>'; 
    product_05 +=              '<span class="search_tag">방문 예약</span>'; 
    product_05 +=              '<span class="search_tag">내방객 사전예약</span>'; 
    product_05 +=              '<span class="search_tag">개인정보보호</span>'; 
    product_05 +=           '</div>'; 
    product_05 +=           '<div class="wrap_govSaas">'; 
    product_05 +=              '<p>정부 공통시스템 연계</p>'; 
    product_05 +=              '<div class="govSaas_tag">'; 
    product_05 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_05 +=                 '<span class="tag">행정표준코드</span>'; 
    product_05 +=              '</div>'; 
    product_05 +=           '</div>'; 
    product_05 +=         '</div>'; 
    product_05 +=         '<div class="wrap_detail_info">'; 
    product_05 +=             '<ul>'; 
    product_05 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_05 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_05 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_05 +=             '</ul>'; 
    product_05 +=          '</div>'; 
    product_05 +=      '</div>';   
    product_05 +=      '<div class="item_buttons">';  
    product_05 +=         '<div class="btn_top">'; 
    product_05 +=            '<div class="wrap_btn">';
    product_05 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_05 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_05 +=               '</div>'; 
    product_05 +=            '</div>'; 
    product_05 +=         '</div>'; 
    product_05 +=         '<div class="btn_bottom">'; 
    product_05 +=            '<div class="wrap_btn">';
    product_05 +=              '<p>기관직접계약</p>'; 
    product_05 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_05 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_05 +=               '</div>'; 
    product_05 +=            '</div>'; 
    product_05 +=            '<div class="wrap_btn">';
    product_05 +=              '<p>중앙조달계약</p>'; 
    product_05 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_05 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_05 +=               '</div>'; 
    product_05 +=            '</div>'; 
    product_05 +=         '</div>'; 
    product_05 +=       '</div>'; 
    product_05 +=    '</div>'; 

    $(".product_card.product_05").html(product_05);

    var product_06 = "";
    product_06 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_06 +=     '<div class="item_head">'; 
    product_06 +=        '<div class="box_line_gray" data-aos="fade" data-aos-delay="100">'; 
    product_06 +=           '<div class="wrap_img">'; 
    product_06 +=              '<img src="../img/saas_img/4_privateSaaS/logo_06.png" alt="하이웍스 단독 구축형 웹메일 로고 이미지" class="viewer"/>'; 
    product_06 +=            '</div>'; 
    product_06 +=        '</div>'; 
    product_06 +=        '<div class="box_filled">'; 
    product_06 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_06 +=        '</div>'; 
    product_06 +=     '</div>';  
    product_06 +=     '<div class="item_middle">'; 
    product_06 +=        '<div class="wrap_name">'; 
    product_06 +=           '<span class="service_category">메일</span>'; 
    product_06 +=           '<span class="product_name">하이웍스 단독 구축형 웹메일</span>'; 
    product_06 +=           '<span class="company_name">가비아</span>'; 
    product_06 +=           '<div class="wrap_serviceTag">'; 
    product_06 +=              '<span class="search_tag">메일</span>'; 
    product_06 +=              '<span class="search_tag">구축형</span>'; 
    product_06 +=              '<span class="search_tag">그룹웨어</span>'; 
    product_06 +=           '</div>'; 
/*     product_06 +=           '<div class="wrap_govSaas">'; 
    product_06 +=              '<p>정부 공통시스템 연계</p>'; 
    product_06 +=              '<div class="govSaas_tag">'; 
    product_06 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_06 +=                 '<span class="tag">행정표준코드</span>'; 
    product_06 +=                 '<span class="tag">LDAP</span>'; 
    product_06 +=              '</div>'; 
    product_06 +=           '</div>';  */
    product_06 +=         '</div>'; 
    product_06 +=         '<div class="wrap_detail_info">'; 
    product_06 +=             '<ul>'; 
    product_06 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_06 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_06 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_06 +=             '</ul>'; 
    product_06 +=          '</div>'; 
    product_06 +=      '</div>';   
    product_06 +=      '<div class="item_buttons">';  
    product_06 +=         '<div class="btn_top">'; 
    product_06 +=            '<div class="wrap_btn">';
    product_06 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_06 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_06 +=               '</div>'; 
    product_06 +=            '</div>'; 
    product_06 +=         '</div>'; 
    product_06 +=         '<div class="btn_bottom">'; 
    product_06 +=            '<div class="wrap_btn">';
    product_06 +=              '<p>기관직접계약</p>'; 
    product_06 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_06 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_06 +=               '</div>'; 
    product_06 +=            '</div>'; 
/*     product_06 +=            '<div class="wrap_btn">';
    product_06 +=              '<p>중앙조달계약</p>'; 
    product_06 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_06 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_06 +=               '</div>'; 
    product_06 +=            '</div>';  */
    product_06 +=         '</div>'; 
    product_06 +=       '</div>'; 
    product_06 +=    '</div>'; 

    $(".product_card.product_06").html(product_06);

    var product_07 = "";
    product_07 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_07 +=     '<div class="item_head">'; 
    product_07 +=        '<div class="box_line_gray" data-aos="fade" data-aos-delay="100">'; 
    product_07 +=           '<div class="wrap_img">'; 
    product_07 +=              '<img src="../img/saas_img/4_privateSaaS/logo_07.png" alt="wehagov (위하고v) 로고 이미지" class="viewer"/>'; 
    product_07 +=            '</div>'; 
    product_07 +=        '</div>'; 
    product_07 +=        '<div class="box_filled">'; 
    product_07 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_07 +=        '</div>'; 
    product_07 +=     '</div>';  
    product_07 +=     '<div class="item_middle">'; 
    product_07 +=        '<div class="wrap_name">'; 
    product_07 +=           '<span class="service_category">협업</span>'; 
    product_07 +=           '<span class="product_name">wehagov (위하고v)</span>'; 
    product_07 +=           '<span class="company_name">더존비즈온</span>'; 
    product_07 +=           '<div class="wrap_serviceTag">'; 
    product_07 +=              '<span class="search_tag">협업</span>'; 
    product_07 +=              '<span class="search_tag">메신저</span>'; 
    product_07 +=              '<span class="search_tag">화상회의</span>'; 
    product_07 +=              '<span class="search_tag">웹 스토리지</span>'; 
    product_07 +=              '<span class="search_tag">거래처 관리</span>'; 
    product_07 +=              '<span class="search_tag">연락처</span>'; 
    product_07 +=              '<span class="search_tag">일정관리</span>'; 
    product_07 +=              '<span class="search_tag">근태관리</span>'; 
    product_07 +=           '</div>'; 
/*     product_07 +=           '<div class="wrap_govSaas">'; 
    product_07 +=              '<p>정부 공통시스템 연계</p>'; 
    product_07 +=              '<div class="govSaas_tag">'; 
    product_07 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_07 +=                 '<span class="tag">행정표준코드</span>'; 
    product_07 +=                 '<span class="tag">LDAP</span>'; 
    product_07 +=              '</div>'; 
    product_07 +=           '</div>';  */
    product_07 +=         '</div>'; 
    product_07 +=         '<div class="wrap_detail_info">'; 
    product_07 +=             '<ul>'; 
    product_07 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_07 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_07 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_07 +=             '</ul>'; 
    product_07 +=          '</div>'; 
    product_07 +=      '</div>';   
    product_07 +=      '<div class="item_buttons">';  
    product_07 +=         '<div class="btn_top">'; 
    product_07 +=            '<div class="wrap_btn">';
    product_07 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_07 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_07 +=               '</div>'; 
    product_07 +=            '</div>'; 
    product_07 +=         '</div>'; 
    product_07 +=         '<div class="btn_bottom">'; 
    product_07 +=            '<div class="wrap_btn">';
    product_07 +=              '<p>기관직접계약</p>'; 
    product_07 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_07 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_07 +=               '</div>'; 
    product_07 +=            '</div>'; 
    product_07 +=            '<div class="wrap_btn">';
    product_07 +=              '<p>중앙조달계약</p>'; 
    product_07 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_07 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_07 +=               '</div>'; 
    product_07 +=            '</div>'; 
    product_07 +=         '</div>'; 
    product_07 +=       '</div>'; 
    product_07 +=    '</div>'; 

    $(".product_card.product_07").html(product_07);

    var product_08 = "";
    product_08 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_08 +=     '<div class="item_head">'; 
    product_08 +=        '<div class="box_line_gray" data-aos="fade" data-aos-delay="100">'; 
    product_08 +=           '<div class="wrap_img">'; 
    product_08 +=              '<img src="../img/saas_img/4_privateSaaS/logo_08.png" alt="클라우다이크 공공기관용 로고 이미지" class="viewer"/>'; 
    product_08 +=            '</div>'; 
    product_08 +=        '</div>'; 
    product_08 +=        '<div class="box_filled">'; 
    product_08 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_08 +=        '</div>'; 
    product_08 +=     '</div>';  
    product_08 +=     '<div class="item_middle">'; 
    product_08 +=        '<div class="wrap_name">'; 
    product_08 +=           '<span class="service_category">협업</span>'; 
    product_08 +=           '<span class="product_name">클라우다이크 공공기관용</span>'; 
    product_08 +=           '<span class="company_name">주식회사 클라우다이크</span>'; 
    product_08 +=           '<div class="wrap_serviceTag">'; 
    product_08 +=              '<span class="search_tag">협업</span>'; 
    product_08 +=              '<span class="search_tag">데이터 관리</span>'; 
    product_08 +=              '<span class="search_tag">데이터저장</span>'; 
    product_08 +=              '<span class="search_tag">다중기기호환</span>'; 
    product_08 +=              '<span class="search_tag">파일공유</span>'; 
    product_08 +=              '<span class="search_tag">문서 뷰어</span>'; 
    product_08 +=           '</div>'; 
/*     product_08 +=           '<div class="wrap_govSaas">'; 
    product_08 +=              '<p>정부 공통시스템 연계</p>'; 
    product_08 +=              '<div class="govSaas_tag">'; 
    product_08 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_08 +=                 '<span class="tag">행정표준코드</span>'; 
    product_08 +=                 '<span class="tag">LDAP</span>'; 
    product_08 +=              '</div>'; 
    product_08 +=           '</div>';  */
    product_08 +=         '</div>'; 
    product_08 +=         '<div class="wrap_detail_info">'; 
    product_08 +=             '<ul>'; 
    product_08 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_08 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_08 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_08 +=             '</ul>'; 
    product_08 +=          '</div>'; 
    product_08 +=      '</div>';   
    product_08 +=      '<div class="item_buttons">';  
    product_08 +=         '<div class="btn_top">'; 
    product_08 +=            '<div class="wrap_btn">';
    product_08 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_08 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_08 +=               '</div>'; 
    product_08 +=            '</div>'; 
    product_08 +=         '</div>'; 
    product_08 +=         '<div class="btn_bottom">'; 
    product_08 +=            '<div class="wrap_btn">';
    product_08 +=              '<p>기관직접계약</p>'; 
    product_08 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_08 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_08 +=               '</div>'; 
    product_08 +=            '</div>'; 
/*     product_08 +=            '<div class="wrap_btn">';
    product_08 +=              '<p>중앙조달계약</p>'; 
    product_08 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_08 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_08 +=               '</div>'; 
    product_08 +=            '</div>';  */
    product_08 +=         '</div>'; 
    product_08 +=       '</div>'; 
    product_08 +=    '</div>'; 

    $(".product_card.product_08").html(product_08);

    var product_09 = "";
    product_09 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_09 +=     '<div class="item_head">'; 
    product_09 +=        '<div class="box_line_gray" data-aos="fade" data-aos-delay="100">'; 
    product_09 +=           '<div class="wrap_img">'; 
    product_09 +=              '<img src="../img/saas_img/4_privateSaaS/logo_09.png" alt="가온누리 (ezEKP365G) 로고 이미지" class="viewer"/>'; 
    product_09 +=            '</div>'; 
    product_09 +=        '</div>'; 
    product_09 +=        '<div class="box_filled">'; 
    product_09 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_09 +=        '</div>'; 
    product_09 +=     '</div>';  
    product_09 +=     '<div class="item_middle">'; 
    product_09 +=        '<div class="wrap_name">'; 
    product_09 +=           '<span class="service_category">협업</span>'; 
    product_09 +=           '<span class="product_name">가온누리 (ezEKP365G)</span>'; 
    product_09 +=           '<span class="company_name">주식회사 가온아이</span>'; 
    product_09 +=           '<div class="wrap_serviceTag">'; 
    product_09 +=              '<span class="search_tag">협업</span>'; 
    product_09 +=              '<span class="search_tag">포탈</span>'; 
    product_09 +=              '<span class="search_tag">전자결재</span>'; 
    product_09 +=              '<span class="search_tag">메일</span>'; 
    product_09 +=              '<span class="search_tag">일정관리</span>'; 
    product_09 +=              '<span class="search_tag">게시판</span>'; 
    product_09 +=              '<span class="search_tag">자원관리</span>'; 
    product_09 +=              '<span class="search_tag">근태관리</span>'; 
    product_09 +=              '<span class="search_tag">업무관리</span>'; 
    product_09 +=           '</div>'; 
/*     product_09 +=           '<div class="wrap_govSaas">'; 
    product_09 +=              '<p>정부 공통시스템 연계</p>'; 
    product_09 +=              '<div class="govSaas_tag">'; 
    product_09 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_09 +=                 '<span class="tag">행정표준코드</span>'; 
    product_09 +=                 '<span class="tag">LDAP</span>'; 
    product_09 +=              '</div>'; 
    product_09 +=           '</div>';  */
    product_09 +=         '</div>'; 
    product_09 +=         '<div class="wrap_detail_info">'; 
    product_09 +=             '<ul>'; 
    product_09 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_09 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_09 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_09 +=             '</ul>'; 
    product_09 +=          '</div>'; 
    product_09 +=      '</div>';   
    product_09 +=      '<div class="item_buttons">';  
    product_09 +=         '<div class="btn_top">'; 
    product_09 +=            '<div class="wrap_btn">';
    product_09 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_09 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_09 +=               '</div>'; 
    product_09 +=            '</div>'; 
    product_09 +=         '</div>'; 
    product_09 +=         '<div class="btn_bottom">'; 
    product_09 +=            '<div class="wrap_btn">';
    product_09 +=              '<p>기관직접계약</p>'; 
    product_09 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_09 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_09 +=               '</div>'; 
    product_09 +=            '</div>'; 
    product_09 +=            '<div class="wrap_btn">';
    product_09 +=              '<p>중앙조달계약</p>'; 
    product_09 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_09 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_09 +=               '</div>'; 
    product_09 +=            '</div>';
    product_09 +=         '</div>'; 
    product_09 +=       '</div>'; 
    product_09 +=    '</div>'; 

    $(".product_card.product_09").html(product_09);

    var product_10 = "";
    product_10 +=  '<div class="product_item" data-aos="fade-up" data-aos-delay="100">';    
    product_10 +=     '<div class="item_head">'; 
    product_10 +=        '<div class="box_line_gray" data-aos="fade" data-aos-delay="100">'; 
    product_10 +=           '<div class="wrap_img">'; 
    product_10 +=              '<img src="../img/saas_img/4_privateSaaS/logo_10.png" alt="올샵(ALL#) ERP 로고 이미지" class="viewer"/>'; 
    product_10 +=            '</div>'; 
    product_10 +=        '</div>'; 
    product_10 +=        '<div class="box_filled">'; 
    product_10 +=          '<p>국가정보원 공시 국가공공기관 도입 가능 <span>클라우드 컴퓨팅 서비스</span></p>'; 
    product_10 +=        '</div>'; 
    product_10 +=     '</div>';  
    product_10 +=     '<div class="item_middle">'; 
    product_10 +=        '<div class="wrap_name">'; 
    product_10 +=           '<span class="service_category">협업</span>'; 
    product_10 +=           '<span class="product_name">올샵(ALL#) ERP</span>'; 
    product_10 +=           '<span class="company_name">씨앤에프 시스템</span>'; 
    product_10 +=           '<div class="wrap_serviceTag">'; 
    product_10 +=              '<span class="search_tag">협업</span>'; 
    product_10 +=              '<span class="search_tag">인사 급여</span>'; 
    product_10 +=              '<span class="search_tag">예산 재무</span>'; 
    product_10 +=              '<span class="search_tag">회계 결산</span>'; 
    product_10 +=              '<span class="search_tag">계약 물품</span>'; 
    product_10 +=              '<span class="search_tag">세무관리</span>'; 
    product_10 +=              '<span class="search_tag">교육 회원</span>'; 
    product_10 +=              '<span class="search_tag">차량관리</span>'; 
    product_10 +=              '<span class="search_tag">자원관리</span>'; 
    product_10 +=           '</div>'; 
/*     product_10 +=           '<div class="wrap_govSaas">'; 
    product_10 +=              '<p>정부 공통시스템 연계</p>'; 
    product_10 +=              '<div class="govSaas_tag">'; 
    product_10 +=                 '<span class="tag">모바일 공무원증</span>'; 
    product_10 +=                 '<span class="tag">행정표준코드</span>'; 
    product_10 +=                 '<span class="tag">LDAP</span>'; 
    product_10 +=              '</div>'; 
    product_10 +=           '</div>';  */
    product_10 +=         '</div>'; 
    product_10 +=         '<div class="wrap_detail_info">'; 
    product_10 +=             '<ul>'; 
    product_10 +=                '<li><span class="label">CSAP 인증</span><span class="info_value">간편</span></li>'; 
    product_10 +=                '<li><span class="label">인증 날짜</span><span class="info_value">2017.07.22 ~ 2026.07.21</span></li>'; 
    product_10 +=                '<li><span class="label">이용 인프라</span><span class="info_value">NHN 클라우드(공공)</span></li>'; 
    product_10 +=             '</ul>'; 
    product_10 +=          '</div>'; 
    product_10 +=      '</div>';   
    product_10 +=      '<div class="item_buttons">';  
    product_10 +=         '<div class="btn_top">'; 
    product_10 +=            '<div class="wrap_btn">';
    product_10 +=               '<div class="round_btn btn_openInNew btn_lined">';
    product_10 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림 - 공식 홈페이지로 이동">공식 사이트</a>';    
    product_10 +=               '</div>'; 
    product_10 +=            '</div>'; 
    product_10 +=         '</div>'; 
    product_10 +=         '<div class="btn_bottom">'; 
    product_10 +=            '<div class="wrap_btn">';
    product_10 +=              '<p>기관직접계약</p>'; 
    product_10 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_10 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 디지털서비스 이용지원 홈페이지의 상세 페이지로 이동">이용지원시스템</a>';    
    product_10 +=               '</div>'; 
    product_10 +=            '</div>'; 
/*     product_10 +=            '<div class="wrap_btn">';
    product_10 +=              '<p>중앙조달계약</p>'; 
    product_10 +=               '<div class="round_btn btn_openInNew btn_filled">';
    product_10 +=                  '<a href="javascript:;" target="_blank" class="link_service_anchor" title="새 창 열림- 조달청 디지철서비스몰의 상세 페이지로 이동">조달청 서비스몰</a>';    
    product_10 +=               '</div>'; 
    product_10 +=            '</div>'; */
    product_10 +=         '</div>'; 
    product_10 +=       '</div>'; 
    product_10 +=    '</div>'; 

    $(".product_card.product_10").html(product_10);
});


